// export const Products = [{
//     ProductID: 120,
//     img: "1.jpeg",
//     ProductName: "Cap",
//     Price: "$10",
//     Stock: 75,
// },
// {
//     ProductID: 145,
//     img: "2.jpeg",
//     ProductName: "Wallet ",
//     Price: "$15",
//     Stock: 90,
// },
// {
//     ProductID: 205,
//     img: "3.jpeg",
//     ProductName: "Ladies Watch ",
//     Price: "$15",
//     Stock: 85,
// },
// {
//     ProductID: 183,
//     img: "4.jpeg",
//     ProductName: "Gents Watch ",
//     Price: "$18",
//     Stock: 65,
// },
// {
//     ProductID: 150,
//     img: "5.jpeg",
//     ProductName: "Bracelet ",
//     Price: "$5",
//     Stock: 260,
// },
// {
//     ProductID: 205,
//     img: "6.jpeg",
//     ProductName: "PackBag",
//     Price: "$25",
//     Stock: 30
// },
// {
//     ProductID: 105,
//     img: "7.jpeg",
//     ProductName: "Ladies Bag",
//     Price: "$35",
//     Stock: 20
// }, {
//     ProductID: 1,
//     img: "9.jpeg",
//     ProductName: "Sneakers Shoe",
//     Price: "$45",
//     Stock: 78,
// },
// {
//     ProductID: 2,
//     img: "101.jpg",
//     ProductName: "radon Shoe",
//     Price: "$25",
//     Stock: 88,
// },
// {
//     ProductID: 3,
//     img: "111.jpg",
//     ProductName: "Headphones",
//     Price: "$38",
//     Stock: 76,
// },
// {
//     ProductID: 4,
//     img: "108.webp",
//     ProductName: "Airdopes 141",
//     Price: "$20",
//     Stock: 45,
// },
// {
//     ProductID: 5,
//     img: "109.jpg",
//     ProductName: "Airdopes M14",
//     Price: "$25",
//     Stock: 27,
// },
// {
//     ProductID: 6,
//     img: "102.jpg",
//     ProductName: "Adidas k65",
//     Price: "$40",
//     Stock: 78,
// },
// {
//     ProductID: 7,
//     img: "110.jpg",
//     ProductName: "Airdopes JH",
//     Price: "$40",
//     Stock: 56,
// },
// {
//     ProductID: 8,
//     img: "103.jpg",
//     ProductName: "Adidas gold M6 Shoe",
//     Price: "$57",
//     Stock: 58,
// },
// {
//     ProductID: 9,
//     img: "112.jpg",
//     ProductName: "Wireless hearphone",
//     Price: "$45",
//     Stock: 48,
// },
// {
//     ProductID: 10,
//     img: "104.jpg",
//     ProductName: "Nike ranger shoe",
//     Price: "$22",
//     Stock: 95,
// },
// {
//     ProductID: 11,
//     img: "111.jpg",
//     ProductName: "Headphone",
//     Price: "$35",
//     Stock: 87,
// },
// {
//     ProductID: 12,
//     img: "108.webp",
//     ProductName: "Airdopes 131",
//     Price: "$65",
//     Stock: 48,
// },
// {
//     ProductID: 13,
//     img: "115.png",
//     ProductName: "Adidas1107 Shoe",
//     Price: "$15",
//     Stock: 54,
// },
// {
//     ProductID: 14,
//     img: "105.jpg",
//     ProductName: "Airmax Shoe",
//     Price: "$48",
//     Stock: 48,
// },
// {
//     ProductID: 15,
//     img: "8.jpeg",
//     ProductName: "Smart watch",
//     Price: "$64",
//     Stock: 54,
// },
// {
//     ProductID: 16,
//     img: "18.jpg",
//     ProductName: "Hand bag",
//     Price: "$55",
//     Stock: 68,
// },
// {
//     ProductID: 17,
//     img: "49.jpg",
//     ProductName: "Luggage bag",
//     Price: "$40",
//     Stock: 34,
// },

// ]